### ISSUE TITLE
decide on error bubbling

### ISSUE THREAD

**Issue by chriskiefer** [Emute-Lab-Instruments/uSEQ#86]
just show first error message

**Comment by monkey-w1n5t0n** [comment]
Yes I agree, otherwise it can get too messy and the additional errors don't really add any useful context.

In cases where the error is not obvious however (e.g. it's hidden deep down in a hierarchy of variables/functions and is only triggered under specific conditions), this may make it a bit harder for users to debug. 

I think that, ideally, when an error occurs we want the following to happen:
1. Print an error message that mentions the name of the function in which the first error occurred, giving useful information that clearly contrasts what was expected and what was received, perhaps even with some suggestions on how to fix it.
2. uSEQ should be able to tell the editor where in the source code that happened, so that we can e.g. highlight the error.
3. If the error happened within the context of an output expr (e.g. when updating a1), then there should also be an additional message informing the user that a1 has been cleared due to the error, because otherwise it will be cleared silently and there may be some confusion about what happened and why.
4. Optionally, the user might want to ask for a stack trace, but we shouldn't show one unless it's requested.

Number 1 is more-or-less in place, number 2 and 4 are perhaps beyond the scope of 1.0, and number 3 should be realistically hackable - I'll look into it.
