### ISSUE TITLE
time not updating in function

### ISSUE THREAD

**Issue by chriskiefer** [Emute-Lab-Instruments/uSEQ#90]
(defun barXTwo [] (* bar 2))
(barXTwo)

>> returns the same number every time.

**Comment by monkey-w1n5t0n** [comment]
Interesting; this has to do with how lambdas are closures that capture the state of any atoms that are being used in their body, so when ```(defun barXTwo [] (* bar 2))``` is evaluated, `barXTwo` will create and store its own environment where `bar` is whatever the value was at the time of definition.

There are a few options:
1. Make lambdas not capture the atoms `t, time, beat, bar, phrase, section`, which will make evaluation fall back on the parent env (which gets automatically updated).
2. Make functions have dynamic (as opposed to lexical) scope, which is a bit of a "smell" in programming languages, but there may actually be some merit to it for a DSL like this.
3. Use variables instead of functions - for example, 
```
(define barXTwo (* bar 2))
(a1 (* 0.5 barXTwo))
```
already works on the `eval_as_signals` branch.

I've gone ahead and implemented number 1 [here](https://github.com/Emute-Lab-Instruments/uSEQ/commit/8d0798e2d1dceb973229ef1c4087b0a57742523c) because it's rather straightforward and seems to behave how we'd want it to.
